export const fonts = [
  {
    fontFamily: "Inter",
    fontWeight: 100,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Thin.woff2') format('woff2'), url('/fonts/Inter-Thin.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 100,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-ThinItalic.woff2') format('woff2'), url('/fonts/Inter-ThinItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 200,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-ExtraLight.woff2') format('woff2'), url('/fonts/Inter-ExtraLight.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 200,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-ExtraLightItalic.woff2') format('woff2'), url('/fonts/Inter-ExtraLightItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 300,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Light.woff2') format('woff2'), url('/fonts/Inter-Light.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 300,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-LightItalic.woff2') format('woff2'), url('/fonts/Inter-LightItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Regular.woff2') format('woff2'), url('/fonts/Inter-Regular.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 400,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Italic.woff2') format('woff2'), url('/fonts/Inter-Italic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 500,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Medium.woff2') format('woff2'), url('/fonts/Inter-Medium.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 500,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-MediumItalic.woff2') format('woff2'), url('/fonts/Inter-MediumItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 600,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-SemiBold.woff2') format('woff2'), url('/fonts/Inter-SemiBold.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 600,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-SemiBoldItalic.woff2') format('woff2'), url('/fonts/Inter-SemiBoldItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 700,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Bold.woff2') format('woff2'), url('/fonts/Inter-Bold.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 700,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-BoldItalic.woff2') format('woff2'), url('/fonts/Inter-BoldItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 800,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-ExtraBold.woff2') format('woff2'), url('/fonts/Inter-ExtraBold.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 800,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-ExtraBoldItalic.woff2') format('woff2'), url('/fonts/Inter-ExtraBoldItalic.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 900,
    fontStyle: "normal",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-Black.woff2') format('woff2'), url('/fonts/Inter-Black.woff') format('woff')",
  },
  {
    fontFamily: "Inter",
    fontWeight: 900,
    fontStyle: "italic",
    fontDisplay: "swap",
    src: "url('/fonts/Inter-BlackItalic.woff2') format('woff2'), url('/fonts/Inter-BlackItalic.woff') format('woff')",
  },
];
